### ISSUE TITLE
Deposit repository to Zenodo including ignored data files

### ISSUE THREAD

**Issue by dhimmel** [greenelab/xswap-analysis#27]
refs https://github.com/greenelab/xswap-manuscript/issues/64

Expanding from https://github.com/greenelab/xswap-analysis/pull/26#issuecomment-1421046442:

> Larger files should be included. Total size of `data/task1` is 13 GB, `data/task3` 3.8 GB, `data/feature-degree` is 1.8 GB. Will need to upload these elsewhere e.g. Zenodo

Zenodo looks like a good option. Doesn't seem like they support directories as per https://github.com/zenodo/zenodo/issues/1089, so we'd want to zip archive prior to upload. We could then include files ignored by `.gitignore` (if we make the zip ourselves). Also should consider not including `.git`.

Then could add a short portion to the readme about how to populate the data directory from the Zenodo download with some shell commands.

**Comment by zietzm** [comment]
As a test, I just zipped the entire `data` directory as is. The file is 16 GB. Should I just upload that to Zenodo?

**Comment by dhimmel** [comment]
> Should I just upload that to Zenodo?

I think we should zip the whole repo perhaps, such that we can address two birds with one deposit:

1. archive of the whole repo (only files tracked via git)
2. archive of the ignored data files

But also okay to do separately.

There is a way to archive releases of GH repos using zenodo described by [GitHub](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content). But that won't get the ignored data, so don't think it makes sense to use.

Best if you can use the zip shell command and share that here so we know exactly how the zip was created.

**Comment by zietzm** [comment]
Okay just finished zipping using the following command:
`zip -r xswap-analysis-submission.zip xswap-analysis -x xswap-analysis/.git/**\*`

The zip file is 16 GB. Is there anything else I should do before submitting it to Zenodo?

**Comment by dhimmel** [comment]
No that looks great, although I think we should rename it `xswap-analysis-v1.0.zip`. We can then also create a release of this repo with a v1.0 tag as well as the manuscript.

Once you rename go ahead and upload!

**Comment by zietzm** [comment]
Uploaded! 

https://zenodo.org/record/7623565

**Comment by dhimmel** [comment]
Great with DOI https://doi.org/10.5281/zenodo.7623565
